############################################################
#
#  Server  服务端相关配置
#
############################################################
# 配置api端口号
server:
  port: 8080

############################################################
#
#  Server   - tomcat 相关配置
#
############################################################
# tomcat 的URI编码
  tomcat:
    uri-encoding: UTF-8


############################################################
#
#  datasource 相关配置
#
############################################################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: quyu
    password: CYbdTF8YwdA2XK3N
    url: jdbc:mysql://47.102.212.159:3306/quyu?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
   
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: 
        commons-log.connection-logger-name: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: admin
        reset-enable: false
        url-pattern: /druid/*
      # 添加过滤规则
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      
############################################################
#
#  mybatis 相关配置
#
############################################################
# mybatis 配置
mybatis:
  type-aliases-package: com.chd.chat.pojo
  mapper-locations: classpath:mapper/*.xml
 
#通用mapper配置
mapper:
  mappers: com.chd.chat.utils.MyMapper
  identity: MYSQL
  
# 分页插件配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


############################################################
#
#  分布式文件系统 FDFS 配置
#
############################################################
fdfs:
  so-timeout: 1501
  connect-timeout: 601 
  #缩略图生成参数
  thumb-image:             
    width: 80
    height: 80
  tracker-list:           
    - 47.102.212.159:22122
    
    
############################################################
#
#  图片保存地址参数相关配置
#
############################################################
imgStorageUrl:
    faceImgUrl: /www/wwwroot/quyu/faceImg/
    qrcodeUrl: /www/wwwroot/quyu/qrcodeImg/

